version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard (solo localhost)
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      # Dashboard solo accesible desde localhost
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=traefik-whitelist"
      - "traefik.http.middlewares.traefik-whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 172.0.0.0/8"

  servicio-analiticas:
    build: ./servicio-analiticas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio-analiticas.rule=PathPrefix(`/reporte`)"
      - "traefik.http.routers.servicio-analiticas.entrypoints=web"
      - "traefik.http.routers.servicio-analiticas.middlewares=auth-basic"
      - "traefik.http.middlewares.auth-basic.basicauth.users=admin:$$apr1$$Z1sbqKz8$$4/g3NzDCqLE/tURphL2vb1"  # admin:secret
      - "traefik.http.services.servicio-analiticas.loadbalancer.server.port=3000"
    networks:
      - traefik_network

  servicio_cliente_1:
    build: ./servicio_cliente_X
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio_cliente_1.rule=PathPrefix(`/cliente/app1`)"
      - "traefik.http.routers.servicio_cliente_1.entrypoints=web"
      - "traefik.http.routers.servicio_cliente_1.middlewares=strip-app1"
      - "traefik.http.middlewares.strip-app1.stripprefix.prefixes=/cliente/app1"
      - "traefik.http.services.servicio_cliente_1.loadbalancer.server.port=3001"
    environment:
      - SERVICE_ID=app1
    networks:
      - traefik_network

  servicio_cliente_2:
    build: ./servicio_cliente_X
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio_cliente_2.rule=PathPrefix(`/cliente/app2`)"
      - "traefik.http.routers.servicio_cliente_2.entrypoints=web"
      - "traefik.http.routers.servicio_cliente_2.middlewares=strip-app2"
      - "traefik.http.middlewares.strip-app2.stripprefix.prefixes=/cliente/app2"
      - "traefik.http.services.servicio_cliente_2.loadbalancer.server.port=3001"
    environment:
      - SERVICE_ID=app2
    networks:
      - traefik_network

  servicio_cliente_3:
    build: ./servicio_cliente_X
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio_cliente_3.rule=PathPrefix(`/cliente/app3`)"
      - "traefik.http.routers.servicio_cliente_3.entrypoints=web"
      - "traefik.http.routers.servicio_cliente_3.middlewares=strip-app3"
      - "traefik.http.middlewares.strip-app3.stripprefix.prefixes=/cliente/app3"
      - "traefik.http.services.servicio_cliente_3.loadbalancer.server.port=3001"
    environment:
      - SERVICE_ID=app3
    networks:
      - traefik_network

  panel-visual:
    build: ./panel-visual
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel-visual.rule=PathPrefix(`/monitor`)"
      - "traefik.http.routers.panel-visual.entrypoints=web"
      - "traefik.http.routers.panel-visual.middlewares=strip-monitor"
      - "traefik.http.middlewares.strip-monitor.stripprefix.prefixes=/monitor"
      - "traefik.http.services.panel-visual.loadbalancer.server.port=80"
    networks:
      - traefik_network


networks:
  traefik_network:
    driver: bridge
